# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_window.ui'
#
# Created: Tue Mar 31 20:00:09 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Add_match(object):
    def setupUi(self, Add_match):
        Add_match.setObjectName("Add_match")
        Add_match.resize(566, 398)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(Add_match)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 551, 381))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setSpacing(12)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.match_type = QtGui.QComboBox(self.horizontalLayoutWidget_3)
        self.match_type.setObjectName("match_type")
        self.match_type.addItem("")
        self.match_type.addItem("")
        self.match_type.addItem("")
        self.match_type.addItem("")
        self.horizontalLayout.addWidget(self.match_type)
        self.lineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.team_number = QtGui.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.team_number.setFont(font)
        self.team_number.setAlignment(QtCore.Qt.AlignCenter)
        self.team_number.setObjectName("team_number")
        self.verticalLayout_2.addWidget(self.team_number)
        self.pushButton = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setHorizontalSpacing(16)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_32 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_32.setObjectName("label_32")
        self.gridLayout_7.addWidget(self.label_32, 1, 0, 1, 1)
        self.label_39 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_39.setObjectName("label_39")
        self.gridLayout_7.addWidget(self.label_39, 9, 0, 1, 1)
        self.label_36 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_7.addWidget(self.label_36, 6, 0, 1, 2)
        self.label_38 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_38.setObjectName("label_38")
        self.gridLayout_7.addWidget(self.label_38, 8, 0, 1, 1)
        self.label_31 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_7.addWidget(self.label_31, 0, 0, 1, 2)
        self.label_37 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_37.setObjectName("label_37")
        self.gridLayout_7.addWidget(self.label_37, 7, 0, 1, 1)
        self.label_35 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_35.setObjectName("label_35")
        self.gridLayout_7.addWidget(self.label_35, 4, 0, 1, 1)
        self.label_33 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_33.setObjectName("label_33")
        self.gridLayout_7.addWidget(self.label_33, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_7.addItem(spacerItem, 5, 0, 1, 2)
        self.label_34 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_34.setObjectName("label_34")
        self.gridLayout_7.addWidget(self.label_34, 3, 0, 1, 1)
        self.label_40 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_40.setObjectName("label_40")
        self.gridLayout_7.addWidget(self.label_40, 10, 0, 1, 1)
        self.label_41 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_7.addWidget(self.label_41, 6, 2, 1, 1)
        self.scouting_table = QtGui.QTableWidget(self.horizontalLayoutWidget_3)
        self.scouting_table.setEnabled(True)
        self.scouting_table.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.scouting_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scouting_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scouting_table.setAutoScroll(False)
        self.scouting_table.setProperty("showDropIndicator", True)
        self.scouting_table.setDragDropOverwriteMode(True)
        self.scouting_table.setShowGrid(True)
        self.scouting_table.setCornerButtonEnabled(False)
        self.scouting_table.setObjectName("scouting_table")
        self.scouting_table.setColumnCount(6)
        self.scouting_table.setRowCount(8)
        item = QtGui.QTableWidgetItem()
        self.scouting_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.scouting_table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.scouting_table.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.scouting_table.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.scouting_table.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.scouting_table.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.scouting_table.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.scouting_table.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.scouting_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.scouting_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.scouting_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.scouting_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.scouting_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.scouting_table.setHorizontalHeaderItem(5, item)
        self.scouting_table.horizontalHeader().setDefaultSectionSize(36)
        self.scouting_table.verticalHeader().setDefaultSectionSize(22)
        self.gridLayout_7.addWidget(self.scouting_table, 0, 2, 6, 1)
        self.auto_check = QtGui.QCheckBox(self.horizontalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.auto_check.sizePolicy().hasHeightForWidth())
        self.auto_check.setSizePolicy(sizePolicy)
        self.auto_check.setText("")
        self.auto_check.setObjectName("auto_check")
        self.gridLayout_7.addWidget(self.auto_check, 1, 1, 1, 1)
        self.tote_check = QtGui.QCheckBox(self.horizontalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tote_check.sizePolicy().hasHeightForWidth())
        self.tote_check.setSizePolicy(sizePolicy)
        self.tote_check.setText("")
        self.tote_check.setObjectName("tote_check")
        self.gridLayout_7.addWidget(self.tote_check, 2, 1, 1, 1)
        self.con_check = QtGui.QCheckBox(self.horizontalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.con_check.sizePolicy().hasHeightForWidth())
        self.con_check.setSizePolicy(sizePolicy)
        self.con_check.setText("")
        self.con_check.setObjectName("con_check")
        self.gridLayout_7.addWidget(self.con_check, 3, 1, 1, 1)
        self.s = QtGui.QCheckBox(self.horizontalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s.sizePolicy().hasHeightForWidth())
        self.s.setSizePolicy(sizePolicy)
        self.s.setText("")
        self.s.setObjectName("s")
        self.gridLayout_7.addWidget(self.s, 4, 1, 1, 1)
        self.hl_spin = QtGui.QSpinBox(self.horizontalLayoutWidget_3)
        self.hl_spin.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.hl_spin.setFrame(False)
        self.hl_spin.setReadOnly(False)
        self.hl_spin.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.hl_spin.setKeyboardTracking(True)
        self.hl_spin.setObjectName("hl_spin")
        self.gridLayout_7.addWidget(self.hl_spin, 7, 1, 1, 1)
        self.landfill_spin = QtGui.QSpinBox(self.horizontalLayoutWidget_3)
        self.landfill_spin.setFrame(False)
        self.landfill_spin.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.landfill_spin.setObjectName("landfill_spin")
        self.gridLayout_7.addWidget(self.landfill_spin, 8, 1, 1, 1)
        self.litter_spin = QtGui.QSpinBox(self.horizontalLayoutWidget_3)
        self.litter_spin.setFrame(False)
        self.litter_spin.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.litter_spin.setSingleStep(2)
        self.litter_spin.setObjectName("litter_spin")
        self.gridLayout_7.addWidget(self.litter_spin, 9, 1, 1, 1)
        self.coop_spin = QtGui.QSpinBox(self.horizontalLayoutWidget_3)
        self.coop_spin.setFrame(False)
        self.coop_spin.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.coop_spin.setMaximum(40)
        self.coop_spin.setSingleStep(20)
        self.coop_spin.setObjectName("coop_spin")
        self.gridLayout_7.addWidget(self.coop_spin, 10, 1, 1, 1)
        self.textEdit = QtGui.QTextEdit(self.horizontalLayoutWidget_3)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_7.addWidget(self.textEdit, 7, 2, 4, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_7)

        self.retranslateUi(Add_match)
        QtCore.QMetaObject.connectSlotsByName(Add_match)
        Add_match.setTabOrder(self.scouting_table, self.auto_check)
        Add_match.setTabOrder(self.auto_check, self.pushButton)
        Add_match.setTabOrder(self.pushButton, self.con_check)
        Add_match.setTabOrder(self.con_check, self.hl_spin)
        Add_match.setTabOrder(self.hl_spin, self.landfill_spin)
        Add_match.setTabOrder(self.landfill_spin, self.litter_spin)
        Add_match.setTabOrder(self.litter_spin, self.coop_spin)
        Add_match.setTabOrder(self.coop_spin, self.textEdit)
        Add_match.setTabOrder(self.textEdit, self.s)
        Add_match.setTabOrder(self.s, self.tote_check)

    def retranslateUi(self, Add_match):
        Add_match.setWindowTitle(QtGui.QApplication.translate("Add_match", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.match_type.setItemText(0, QtGui.QApplication.translate("Add_match", "qm", None, QtGui.QApplication.UnicodeUTF8))
        self.match_type.setItemText(1, QtGui.QApplication.translate("Add_match", "qf", None, QtGui.QApplication.UnicodeUTF8))
        self.match_type.setItemText(2, QtGui.QApplication.translate("Add_match", "sf", None, QtGui.QApplication.UnicodeUTF8))
        self.match_type.setItemText(3, QtGui.QApplication.translate("Add_match", "f", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setPlaceholderText(QtGui.QApplication.translate("Add_match", "Match #", None, QtGui.QApplication.UnicodeUTF8))
        self.team_number.setText(QtGui.QApplication.translate("Add_match", "846", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Add_match", "Add New", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("Add_match", "Auto Set", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("Add_match", "Litter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("Add_match", "Tele-Op", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("Add_match", "Landfill", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("Add_match", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("Add_match", "Human Load", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("Add_match", "Stacked Set", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("Add_match", "Tote Set", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("Add_match", "Container Set", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("Add_match", "Coopertition", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("Add_match", "Comments", None, QtGui.QApplication.UnicodeUTF8))
        self.scouting_table.verticalHeaderItem(0).setText(QtGui.QApplication.translate("Add_match", "LIT", None, QtGui.QApplication.UnicodeUTF8))
        self.scouting_table.verticalHeaderItem(1).setText(QtGui.QApplication.translate("Add_match", "CON", None, QtGui.QApplication.UnicodeUTF8))
        self.scouting_table.verticalHeaderItem(2).setText(QtGui.QApplication.translate("Add_match", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.scouting_table.verticalHeaderItem(3).setText(QtGui.QApplication.translate("Add_match", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.scouting_table.verticalHeaderItem(4).setText(QtGui.QApplication.translate("Add_match", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.scouting_table.verticalHeaderItem(5).setText(QtGui.QApplication.translate("Add_match", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.scouting_table.verticalHeaderItem(6).setText(QtGui.QApplication.translate("Add_match", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.scouting_table.verticalHeaderItem(7).setText(QtGui.QApplication.translate("Add_match", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.scouting_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Add_match", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.scouting_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Add_match", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.scouting_table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Add_match", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.scouting_table.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Add_match", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.scouting_table.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Add_match", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.scouting_table.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Add_match", "6", None, QtGui.QApplication.UnicodeUTF8))

