# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Fri Apr  3 14:46:43 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(761, 541)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 751, 481))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.choose_title = QtGui.QLabel(self.horizontalLayoutWidget)
        self.choose_title.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.choose_title.setFont(font)
        self.choose_title.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.choose_title.setMargin(0)
        self.choose_title.setObjectName("choose_title")
        self.verticalLayout.addWidget(self.choose_title)
        self.team_selection = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.team_selection.setObjectName("team_selection")
        self.verticalLayout.addWidget(self.team_selection)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 32)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.team_number_text = QtGui.QLabel(self.horizontalLayoutWidget)
        self.team_number_text.setMaximumSize(QtCore.QSize(100, 16777215))
        self.team_number_text.setObjectName("team_number_text")
        self.gridLayout_2.addWidget(self.team_number_text, 0, 0, 1, 1)
        self.rank_text = QtGui.QLabel(self.horizontalLayoutWidget)
        self.rank_text.setMaximumSize(QtCore.QSize(120, 16777215))
        self.rank_text.setObjectName("rank_text")
        self.gridLayout_2.addWidget(self.rank_text, 2, 0, 1, 1)
        self.dpr_text = QtGui.QLabel(self.horizontalLayoutWidget)
        self.dpr_text.setObjectName("dpr_text")
        self.gridLayout_2.addWidget(self.dpr_text, 5, 0, 1, 1)
        self.opr_text = QtGui.QLabel(self.horizontalLayoutWidget)
        self.opr_text.setObjectName("opr_text")
        self.gridLayout_2.addWidget(self.opr_text, 4, 0, 1, 1)
        self.dpr = QtGui.QLabel(self.horizontalLayoutWidget)
        self.dpr.setObjectName("dpr")
        self.gridLayout_2.addWidget(self.dpr, 5, 1, 1, 1)
        self.team_name_text = QtGui.QLabel(self.horizontalLayoutWidget)
        self.team_name_text.setMaximumSize(QtCore.QSize(120, 16777215))
        self.team_name_text.setObjectName("team_name_text")
        self.gridLayout_2.addWidget(self.team_name_text, 1, 0, 1, 1)
        self.team_name = QtGui.QLabel(self.horizontalLayoutWidget)
        self.team_name.setMinimumSize(QtCore.QSize(80, 0))
        self.team_name.setMaximumSize(QtCore.QSize(80, 16777215))
        self.team_name.setScaledContents(False)
        self.team_name.setWordWrap(True)
        self.team_name.setObjectName("team_name")
        self.gridLayout_2.addWidget(self.team_name, 1, 1, 1, 1)
        self.team_number = QtGui.QLabel(self.horizontalLayoutWidget)
        self.team_number.setMaximumSize(QtCore.QSize(100, 16777215))
        self.team_number.setWordWrap(True)
        self.team_number.setObjectName("team_number")
        self.gridLayout_2.addWidget(self.team_number, 0, 1, 1, 1)
        self.rank = QtGui.QLabel(self.horizontalLayoutWidget)
        self.rank.setWordWrap(True)
        self.rank.setObjectName("rank")
        self.gridLayout_2.addWidget(self.rank, 2, 1, 1, 1)
        self.opr = QtGui.QLabel(self.horizontalLayoutWidget)
        self.opr.setObjectName("opr")
        self.gridLayout_2.addWidget(self.opr, 4, 1, 1, 1)
        self.matches_played = QtGui.QLabel(self.horizontalLayoutWidget)
        self.matches_played.setObjectName("matches_played")
        self.gridLayout_2.addWidget(self.matches_played, 3, 1, 1, 1)
        self.matches_played_text = QtGui.QLabel(self.horizontalLayoutWidget)
        self.matches_played_text.setMaximumSize(QtCore.QSize(120, 16777215))
        self.matches_played_text.setObjectName("matches_played_text")
        self.gridLayout_2.addWidget(self.matches_played_text, 3, 0, 1, 1)
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 6, 0, 1, 1)
        self.ccwm = QtGui.QLabel(self.horizontalLayoutWidget)
        self.ccwm.setObjectName("ccwm")
        self.gridLayout_2.addWidget(self.ccwm, 6, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.tabWidget = QtGui.QTabWidget(self.horizontalLayoutWidget)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.general_tab = QtGui.QWidget()
        self.general_tab.setEnabled(True)
        self.general_tab.setObjectName("general_tab")
        self.gridLayoutWidget_3 = QtGui.QWidget(self.general_tab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 560, 431))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_6 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gen_cont = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.gen_cont.setFocusPolicy(QtCore.Qt.NoFocus)
        self.gen_cont.setFlat(True)
        self.gen_cont.setObjectName("gen_cont")
        self.gridLayout_6.addWidget(self.gen_cont, 2, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 1, 4, 1, 1)
        self.label_23 = QtGui.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_6.addWidget(self.label_23, 1, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_6.addWidget(self.label_21, 1, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_6.addWidget(self.label_25, 1, 3, 1, 1)
        self.label_24 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_6.addWidget(self.label_24, 1, 2, 1, 1)
        self.gen_tote = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.gen_tote.setFocusPolicy(QtCore.Qt.NoFocus)
        self.gen_tote.setFlat(True)
        self.gen_tote.setObjectName("gen_tote")
        self.gridLayout_6.addWidget(self.gen_tote, 2, 4, 1, 1)
        self.gen_score = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.gen_score.setFocusPolicy(QtCore.Qt.NoFocus)
        self.gen_score.setAutoRepeat(False)
        self.gen_score.setAutoExclusive(False)
        self.gen_score.setFlat(True)
        self.gen_score.setObjectName("gen_score")
        self.gridLayout_6.addWidget(self.gen_score, 2, 0, 1, 1)
        self.gen_coop = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.gen_coop.setFocusPolicy(QtCore.Qt.NoFocus)
        self.gen_coop.setFlat(True)
        self.gen_coop.setObjectName("gen_coop")
        self.gridLayout_6.addWidget(self.gen_coop, 2, 2, 1, 1)
        self.gen_litter = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.gen_litter.setFocusPolicy(QtCore.Qt.NoFocus)
        self.gen_litter.setFlat(True)
        self.gen_litter.setObjectName("gen_litter")
        self.gridLayout_6.addWidget(self.gen_litter, 2, 3, 1, 1)
        self.label_26 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_26.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_26.setObjectName("label_26")
        self.gridLayout_6.addWidget(self.label_26, 0, 0, 1, 6)
        self.label_42 = QtGui.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.gridLayout_6.addWidget(self.label_42, 1, 5, 1, 1)
        self.gen_auto = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.gen_auto.setFocusPolicy(QtCore.Qt.NoFocus)
        self.gen_auto.setFlat(True)
        self.gen_auto.setObjectName("gen_auto")
        self.gridLayout_6.addWidget(self.gen_auto, 2, 5, 1, 1)
        self.graph_area = QtGui.QVBoxLayout()
        self.graph_area.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.graph_area.setObjectName("graph_area")
        self.gridLayout_6.addLayout(self.graph_area, 3, 0, 1, 6)
        self.tabWidget.addTab(self.general_tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.tab_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(9, 9, 531, 411))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.matches_list = QtGui.QListWidget(self.horizontalLayoutWidget_2)
        self.matches_list.setMaximumSize(QtCore.QSize(100, 16777215))
        self.matches_list.setObjectName("matches_list")
        self.horizontalLayout_2.addWidget(self.matches_list)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 3)
        self.label_5 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.matches_blue_3 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.matches_blue_3.setAlignment(QtCore.Qt.AlignCenter)
        self.matches_blue_3.setObjectName("matches_blue_3")
        self.gridLayout.addWidget(self.matches_blue_3, 1, 5, 1, 1)
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 3)
        self.label_7 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.matches_red_1 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.matches_red_1.setMinimumSize(QtCore.QSize(0, 50))
        self.matches_red_1.setMaximumSize(QtCore.QSize(16777215, 50))
        self.matches_red_1.setAlignment(QtCore.Qt.AlignCenter)
        self.matches_red_1.setObjectName("matches_red_1")
        self.gridLayout.addWidget(self.matches_red_1, 1, 0, 1, 1)
        self.matches_blue_1 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.matches_blue_1.setAlignment(QtCore.Qt.AlignCenter)
        self.matches_blue_1.setObjectName("matches_blue_1")
        self.gridLayout.addWidget(self.matches_blue_1, 1, 3, 1, 1)
        self.matches_red_2 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.matches_red_2.setAlignment(QtCore.Qt.AlignCenter)
        self.matches_red_2.setObjectName("matches_red_2")
        self.gridLayout.addWidget(self.matches_red_2, 1, 1, 1, 1)
        self.matches_red_3 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.matches_red_3.setAlignment(QtCore.Qt.AlignCenter)
        self.matches_red_3.setObjectName("matches_red_3")
        self.gridLayout.addWidget(self.matches_red_3, 1, 2, 1, 1)
        self.matches_blue_2 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.matches_blue_2.setAlignment(QtCore.Qt.AlignCenter)
        self.matches_blue_2.setObjectName("matches_blue_2")
        self.gridLayout.addWidget(self.matches_blue_2, 1, 4, 1, 1)
        self.label_8 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 2, 5, 1, 1)
        self.label_28 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 3, 5, 1, 1)
        self.label_29 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 4, 5, 1, 1)
        self.label_30 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 5, 5, 1, 1)
        self.matches_b_foul = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.matches_b_foul.setAlignment(QtCore.Qt.AlignCenter)
        self.matches_b_foul.setObjectName("matches_b_foul")
        self.gridLayout.addWidget(self.matches_b_foul, 5, 4, 1, 1)
        self.matches_b_tele = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.matches_b_tele.setAlignment(QtCore.Qt.AlignCenter)
        self.matches_b_tele.setObjectName("matches_b_tele")
        self.gridLayout.addWidget(self.matches_b_tele, 4, 4, 1, 1)
        self.matches_b_auto = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.matches_b_auto.setAlignment(QtCore.Qt.AlignCenter)
        self.matches_b_auto.setObjectName("matches_b_auto")
        self.gridLayout.addWidget(self.matches_b_auto, 3, 4, 1, 1)
        self.matches_b_score = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.matches_b_score.setAlignment(QtCore.Qt.AlignCenter)
        self.matches_b_score.setObjectName("matches_b_score")
        self.gridLayout.addWidget(self.matches_b_score, 2, 4, 1, 1)
        self.matches_r_foul = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.matches_r_foul.setAlignment(QtCore.Qt.AlignCenter)
        self.matches_r_foul.setObjectName("matches_r_foul")
        self.gridLayout.addWidget(self.matches_r_foul, 5, 1, 1, 1)
        self.matches_r_tele = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.matches_r_tele.setAlignment(QtCore.Qt.AlignCenter)
        self.matches_r_tele.setObjectName("matches_r_tele")
        self.gridLayout.addWidget(self.matches_r_tele, 4, 1, 1, 1)
        self.matches_r_auto = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.matches_r_auto.setAlignment(QtCore.Qt.AlignCenter)
        self.matches_r_auto.setObjectName("matches_r_auto")
        self.gridLayout.addWidget(self.matches_r_auto, 3, 1, 1, 1)
        self.matches_r_score = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.matches_r_score.setAlignment(QtCore.Qt.AlignCenter)
        self.matches_r_score.setObjectName("matches_r_score")
        self.gridLayout.addWidget(self.matches_r_score, 2, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab_2, "")
        self.scouting = QtGui.QWidget()
        self.scouting.setObjectName("scouting")
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.scouting)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 571, 421))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setSpacing(12)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scouting_list = QtGui.QListWidget(self.horizontalLayoutWidget_3)
        self.scouting_list.setMaximumSize(QtCore.QSize(100, 16777215))
        self.scouting_list.setObjectName("scouting_list")
        self.verticalLayout_2.addWidget(self.scouting_list)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton.setMaximumSize(QtCore.QSize(35, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.edit_button = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.edit_button.setMaximumSize(QtCore.QSize(20, 16777215))
        self.edit_button.setObjectName("edit_button")
        self.horizontalLayout_4.addWidget(self.edit_button)
        self.delete_button = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.delete_button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout_4.addWidget(self.delete_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setHorizontalSpacing(16)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_39 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_39.setObjectName("label_39")
        self.gridLayout_7.addWidget(self.label_39, 9, 0, 1, 1)
        self.scout_litter = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.scout_litter.setObjectName("scout_litter")
        self.gridLayout_7.addWidget(self.scout_litter, 9, 1, 1, 1)
        self.scout_auto_set = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.scout_auto_set.setObjectName("scout_auto_set")
        self.gridLayout_7.addWidget(self.scout_auto_set, 1, 1, 1, 1)
        self.label_36 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_7.addWidget(self.label_36, 6, 0, 1, 2)
        self.label_38 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_38.setObjectName("label_38")
        self.gridLayout_7.addWidget(self.label_38, 8, 0, 1, 1)
        self.label_31 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_31.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_7.addWidget(self.label_31, 0, 0, 1, 2)
        self.label_37 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_37.setObjectName("label_37")
        self.gridLayout_7.addWidget(self.label_37, 7, 0, 1, 1)
        self.label_35 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_35.setObjectName("label_35")
        self.gridLayout_7.addWidget(self.label_35, 4, 0, 1, 1)
        self.label_32 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_32.setObjectName("label_32")
        self.gridLayout_7.addWidget(self.label_32, 1, 0, 1, 1)
        self.label_33 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_33.setObjectName("label_33")
        self.gridLayout_7.addWidget(self.label_33, 2, 0, 1, 1)
        self.scout_landfill = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.scout_landfill.setObjectName("scout_landfill")
        self.gridLayout_7.addWidget(self.scout_landfill, 8, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_7.addItem(spacerItem, 5, 0, 1, 2)
        self.scout_human = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.scout_human.setObjectName("scout_human")
        self.gridLayout_7.addWidget(self.scout_human, 7, 1, 1, 1)
        self.label_34 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_34.setObjectName("label_34")
        self.gridLayout_7.addWidget(self.label_34, 3, 0, 1, 1)
        self.scout_coop = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.scout_coop.setObjectName("scout_coop")
        self.gridLayout_7.addWidget(self.scout_coop, 10, 1, 1, 1)
        self.scout_tote_set = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.scout_tote_set.setObjectName("scout_tote_set")
        self.gridLayout_7.addWidget(self.scout_tote_set, 2, 1, 1, 1)
        self.scout_cont_set = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.scout_cont_set.setObjectName("scout_cont_set")
        self.gridLayout_7.addWidget(self.scout_cont_set, 3, 1, 1, 1)
        self.label_40 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_40.setObjectName("label_40")
        self.gridLayout_7.addWidget(self.label_40, 10, 0, 1, 1)
        self.scout_stack_set = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.scout_stack_set.setObjectName("scout_stack_set")
        self.gridLayout_7.addWidget(self.scout_stack_set, 4, 1, 1, 1)
        self.label_41 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_7.addWidget(self.label_41, 6, 2, 1, 1)
        self.scouting_comments = QtGui.QTextBrowser(self.horizontalLayoutWidget_3)
        self.scouting_comments.setMaximumSize(QtCore.QSize(16777215, 150))
        self.scouting_comments.setObjectName("scouting_comments")
        self.gridLayout_7.addWidget(self.scouting_comments, 7, 2, 4, 1)
        self.scouting_table = QtGui.QTableWidget(self.horizontalLayoutWidget_3)
        self.scouting_table.setEnabled(True)
        self.scouting_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scouting_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scouting_table.setAutoScroll(True)
        self.scouting_table.setObjectName("scouting_table")
        self.scouting_table.setColumnCount(6)
        self.scouting_table.setRowCount(8)
        item = QtGui.QTableWidgetItem()
        self.scouting_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.scouting_table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.scouting_table.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.scouting_table.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.scouting_table.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.scouting_table.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.scouting_table.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.scouting_table.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.scouting_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.scouting_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.scouting_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.scouting_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.scouting_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.scouting_table.setHorizontalHeaderItem(5, item)
        self.scouting_table.horizontalHeader().setDefaultSectionSize(36)
        self.scouting_table.verticalHeader().setDefaultSectionSize(22)
        self.gridLayout_7.addWidget(self.scouting_table, 0, 2, 6, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_7)
        self.tabWidget.addTab(self.scouting, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.save_button = QtGui.QPushButton(self.centralwidget)
        self.save_button.setGeometry(QtCore.QRect(670, 485, 88, 28))
        self.save_button.setObjectName("save_button")
        self.update_button = QtGui.QPushButton(self.centralwidget)
        self.update_button.setGeometry(QtCore.QRect(0, 485, 88, 28))
        self.update_button.setObjectName("update_button")
        self.link_button = QtGui.QPushButton(self.centralwidget)
        self.link_button.setGeometry(QtCore.QRect(240, 485, 161, 28))
        self.link_button.setObjectName("link_button")
        self.link_button_2 = QtGui.QPushButton(self.centralwidget)
        self.link_button_2.setGeometry(QtCore.QRect(410, 485, 161, 28))
        self.link_button_2.setObjectName("link_button_2")
        self.change_event_button = QtGui.QPushButton(self.centralwidget)
        self.change_event_button.setGeometry(QtCore.QRect(100, 485, 101, 28))
        self.change_event_button.setObjectName("change_event_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 761, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.choose_title.setText(QtGui.QApplication.translate("MainWindow", " Choose Team Number", None, QtGui.QApplication.UnicodeUTF8))
        self.team_number_text.setText(QtGui.QApplication.translate("MainWindow", "Team Number", None, QtGui.QApplication.UnicodeUTF8))
        self.rank_text.setText(QtGui.QApplication.translate("MainWindow", "Rank", None, QtGui.QApplication.UnicodeUTF8))
        self.dpr_text.setText(QtGui.QApplication.translate("MainWindow", "DPR", None, QtGui.QApplication.UnicodeUTF8))
        self.opr_text.setText(QtGui.QApplication.translate("MainWindow", "OPR", None, QtGui.QApplication.UnicodeUTF8))
        self.dpr.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.team_name_text.setText(QtGui.QApplication.translate("MainWindow", "Team Name", None, QtGui.QApplication.UnicodeUTF8))
        self.team_name.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.team_number.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.rank.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.opr.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.matches_played.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.matches_played_text.setText(QtGui.QApplication.translate("MainWindow", "Matches", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "CCWM", None, QtGui.QApplication.UnicodeUTF8))
        self.ccwm.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.gen_cont.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Tote", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Container", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Score", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Litter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Coop", None, QtGui.QApplication.UnicodeUTF8))
        self.gen_tote.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.gen_score.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.gen_coop.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.gen_litter.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", " Average", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("MainWindow", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.gen_auto.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.general_tab), QtGui.QApplication.translate("MainWindow", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "  Red", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Score", None, QtGui.QApplication.UnicodeUTF8))
        self.matches_blue_3.setText(QtGui.QApplication.translate("MainWindow", "Blue T 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Blue  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Tele-Op", None, QtGui.QApplication.UnicodeUTF8))
        self.matches_red_1.setText(QtGui.QApplication.translate("MainWindow", "Red T 1", None, QtGui.QApplication.UnicodeUTF8))
        self.matches_blue_1.setText(QtGui.QApplication.translate("MainWindow", "Blue T 1", None, QtGui.QApplication.UnicodeUTF8))
        self.matches_red_2.setText(QtGui.QApplication.translate("MainWindow", "Red T 2", None, QtGui.QApplication.UnicodeUTF8))
        self.matches_red_3.setText(QtGui.QApplication.translate("MainWindow", "Red T 3", None, QtGui.QApplication.UnicodeUTF8))
        self.matches_blue_2.setText(QtGui.QApplication.translate("MainWindow", "Blue T 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Foul", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Score", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "Tele-Op", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Foul", None, QtGui.QApplication.UnicodeUTF8))
        self.matches_b_foul.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.matches_b_tele.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.matches_b_auto.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.matches_b_score.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.matches_r_foul.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.matches_r_tele.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.matches_r_auto.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.matches_r_score.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Matches", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_button.setText(QtGui.QApplication.translate("MainWindow", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_button.setText(QtGui.QApplication.translate("MainWindow", "Del", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("MainWindow", "Container", None, QtGui.QApplication.UnicodeUTF8))
        self.scout_litter.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.scout_auto_set.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "Tele-Op", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("MainWindow", "Landfill", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("MainWindow", "Human Load", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("MainWindow", "Stacked Set", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "Auto Set", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "Tote Set", None, QtGui.QApplication.UnicodeUTF8))
        self.scout_landfill.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.scout_human.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "Container Set", None, QtGui.QApplication.UnicodeUTF8))
        self.scout_coop.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.scout_tote_set.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.scout_cont_set.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("MainWindow", "Coopertition", None, QtGui.QApplication.UnicodeUTF8))
        self.scout_stack_set.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("MainWindow", "Comments", None, QtGui.QApplication.UnicodeUTF8))
        self.scouting_table.verticalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "LIT", None, QtGui.QApplication.UnicodeUTF8))
        self.scouting_table.verticalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "CON", None, QtGui.QApplication.UnicodeUTF8))
        self.scouting_table.verticalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.scouting_table.verticalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.scouting_table.verticalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.scouting_table.verticalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.scouting_table.verticalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.scouting_table.verticalHeaderItem(7).setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.scouting_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.scouting_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.scouting_table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.scouting_table.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.scouting_table.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.scouting_table.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scouting), QtGui.QApplication.translate("MainWindow", "Scouting", None, QtGui.QApplication.UnicodeUTF8))
        self.save_button.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.update_button.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.link_button.setText(QtGui.QApplication.translate("MainWindow", "Blue Alliance Event Page", None, QtGui.QApplication.UnicodeUTF8))
        self.link_button_2.setText(QtGui.QApplication.translate("MainWindow", "Blue Alliance Team Page", None, QtGui.QApplication.UnicodeUTF8))
        self.change_event_button.setText(QtGui.QApplication.translate("MainWindow", "Change Event", None, QtGui.QApplication.UnicodeUTF8))

